CREATE TABLE `anx` (
  `ID_ORDEM` int NOT NULL AUTO_INCREMENT,
  `EMP_ORDEM` varchar(3) NOT NULL,
  `CODIGO_ORDEM` int NOT NULL,
  `EMP_CODIGO` varchar(30) NOT NULL,
  `FILIAL` varchar(3) NOT NULL,
  `DATA` date NOT NULL,
  `OPERACAO` varchar(10) NOT NULL,
  `TIPO` varchar(50) NOT NULL,
  `DATA_OPERACAO` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `USER_OPERACAO` varchar(30) NOT NULL,
  PRIMARY KEY (`ID_ORDEM`)
) ENGINE=MyISAM AUTO_INCREMENT=105335 DEFAULT CHARSET=latin1;
