SELECT DISTINCT A.DOCUMENTO FROM SCCD_APP A
WHERE 1=1
AND A.DT_AJUSTE is NULL
AND A.ID NOT IN ( SELECT MIN(B.ID) ID FROM SCCD_APP B 
                  WHERE B.DOCUMENTO = A.DOCUMENTO
                  GROUP BY B.DOCUMENTO,B.ARQUIVO,B.OPERACAO,B.IMAGEM_ID )
ORDER BY A.DOCUMENTO
;

SELECT * FROM SCCD_APP A
WHERE 1=1
AND A.DT_AJUSTE is NULL
AND A.ID NOT IN ( SELECT MIN(B.ID) ID FROM SCCD_APP B 
                  WHERE B.DOCUMENTO = A.DOCUMENTO
                  GROUP BY B.DOCUMENTO,B.ARQUIVO,B.OPERACAO,B.IMAGEM_ID )
ORDER BY A.ID
